# Generated by Django 2.1.1 on 2018-10-03 11:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_auto_20180918_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 10, 3, 11, 1, 12, 778085, tzinfo=utc))),
            ],
        ),
    ]
