# Generated by Django 2.1.1 on 2018-10-13 13:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 13, 13, 40, 42, 201828, tzinfo=utc)),
        ),
    ]
