# Generated by Django 2.1.1 on 2018-09-18 01:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180916_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 18, 1, 25, 21, 146964, tzinfo=utc)),
        ),
    ]
