# Generated by Django 2.1.1 on 2018-09-22 11:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180918_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 22, 11, 24, 20, 91141, tzinfo=utc)),
        ),
    ]
