# Generated by Django 2.1.1 on 2018-10-14 12:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20181013_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 12, 59, 29, 447250, tzinfo=utc)),
        ),
    ]
